// Generated by CoffeeScript 1.6.3
(function() {
  describe("Coffeescript tests using jasmine-given", function() {
    return describe("Get Neighbors", function() {
      var expectedCells, neighbors;
      neighbors = null;
      Given(function() {
        return neighbors = [];
      });
      When(function() {
        return neighbors = LIFE.getNeighbors(1, 1);
      });
      Then(function() {
        return neighbors.length = 8;
      });
      expectedCells = null;
      Given(function() {
        return expectedCells = [];
      });
      When(function() {
        return expectedCells = [[0, 0], [0, 1], [0, 2], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]];
      });
      return Then(function() {
        return expect(LIFE.getNeighbors(1, 1)).toEqual(expectedCells);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=LifeSpecCoffee.map
*/
